version: '3'
services:
    write-template-yaml:
      build: ./docker
      container_name: write-template-yaml
      environment:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_REGION
        - AWS_DEFAULT_REGION
        - AWS_PROFILE
        - BACKLOG_API_KEY
        - TZ=Asia/Tokyo
      volumes:
        - $HOME/.aws:/root/.aws
        - .:/work
      working_dir: /work
      entrypoint: ruby write-template-yaml.rb
